# Generated by Django 3.2 on 2021-04-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='id',
        ),
        migrations.AlterField(
            model_name='news',
            name='news_url',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
