# Generated by Django 3.2 on 2021-04-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0002_auto_20210420_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='id',
            field=models.AutoField(auto_created=True, default='default_value', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='news_url',
            field=models.CharField(max_length=200),
        ),
    ]
