# Generated by Django 3.2 on 2021-04-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0003_auto_20210420_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_hype_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
